---
all:
  children:
    dns_resolvers:
      hosts:
        dns-01:
          ansible_host: 192.168.2.51
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/proxmox-automation
        dns-02:
          ansible_host: 192.168.2.50
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/proxmox-automation

    proxmox_time_servers:
      hosts:
        PROXMOX:
          ansible_host: 192.168.2.70
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/proxmox-root
          chrony_expected_hostname: PROXMOX
          chrony_expected_ipv4: 192.168.2.70
          chrony_expected_interface: vmbr0
          chrony_service_alias: ntp-01
        Proxmox-2:
          ansible_host: 192.168.2.71
          ansible_user: root
          ansible_ssh_private_key_file: ~/.ssh/proxmox-root
          chrony_expected_hostname: Proxmox-2
          chrony_expected_ipv4: 192.168.2.71
          chrony_expected_interface: vmbr0
          chrony_service_alias: ntp-02
