---
- name: Restart unbound
  ansible.builtin.systemd_service:
    name: unbound
    state: restarted
    enabled: true

- name: Restart Pi-hole FTL
  ansible.builtin.systemd_service:
    name: pihole-FTL
    state: restarted
    enabled: true

- name: Update Pi-hole gravity
  ansible.builtin.command:
    argv:
      - /usr/local/bin/pihole
      - updateGravity
  changed_when: true
